apiVersion: v1
kind: Namespace
metadata:
  name: autoecops-core
  labels:
    app.kubernetes.io/part-of: autoecops-ecosystem
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: autoecops-platform-01
  labels:
    app.kubernetes.io/part-of: autoecops-ecosystem
    platform: platform-01
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: autoecops-platform-02
  labels:
    app.kubernetes.io/part-of: autoecops-ecosystem
    platform: platform-02
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: autoecops-platform-03
  labels:
    app.kubernetes.io/part-of: autoecops-ecosystem
    platform: platform-03
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: autoecops-observability
  labels:
    app.kubernetes.io/part-of: autoecops-ecosystem
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/part-of: autoecops-ecosystem
