name = "contracts-l1-web"
compatibility_date = "2024-02-12"
pages_build_output_dir = ".next"

[vars]
NEXT_PUBLIC_APP_NAME = "Contracts-L1"
NEXT_PUBLIC_APP_VERSION = "1.0.0"

[env.production.vars]
NODE_VERSION = "20"
PNPM_VERSION = "8"
