[build]
command = "npx next build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Domain configuration
[[redirects]]
from = "https://www.autoecoops.io/*"
to = "https://autoecoops.io/:splat"
status = 301
force = true
